apiVersion: v1
kind: Service
metadata:
  name: station-service
  namespace: lastmile
spec:
  type: ClusterIP
  selector:
    app: station-service
  ports:
    - protocol: TCP
      port: 9091     # Service port
      targetPort: 9091   # Container port