apiVersion: v1
kind: Service
metadata:
  name: driver-service
  namespace: lastmile
spec:
  type: ClusterIP
  selector:
    app: driver-service
  ports:
    - protocol: TCP
      port: 8082     # Service port
      targetPort: 8082   # Container port
