apiVersion: v1
kind: Service
metadata:
  name: location-service
  namespace: lastmile
spec:
  type: ClusterIP
  selector:
    app: location-service
  ports:
    - protocol: TCP
      port: 9095    # Service port
      targetPort: 9095   # Container port