apiVersion: v1
kind: Service
metadata:
  name: trip-service
  namespace: lastmile
spec:
  type: NodePort
  selector:
    app: trip-service
  ports:
    - protocol: TCP
      port: 8084    # Service port
      targetPort: 8084   # Container port
