apiVersion: v1
kind: Service
metadata:
  name: matching-service
  namespace: lastmile
spec:
  type: ClusterIP
  selector:
    app: matching-service
  ports:
    - protocol: TCP
      port: 8085    # Service port
      targetPort: 8085   # Container port
