apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: lastmile
spec:
  type: ClusterIP
  selector:
    app: notification-service
  ports:
    - protocol: TCP
      port: 8086     # Service port
      targetPort: 8086   # Container port