apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: lastmile
spec:
  type: NodePort
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: 8081     # Service port
      targetPort: 8081   # Container port