apiVersion: v1
kind: Service
metadata:
  name: rider-service
  namespace: lastmile
spec:
  type: ClusterIP
  selector:
    app: rider-service
  ports:
    - protocol: TCP
      port: 8083     # Service port
      targetPort: 8083   # Container port