apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: lastmile
spec:
  clusterIP: None
  ports:
    - port: 9092
  selector:
    app: kafka
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  namespace: lastmile
spec:
  type: ClusterIP
  ports:
    - name: broker
      port: 9092
      targetPort: 9092
  selector:
    app: kafka
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: lastmile
spec:
  serviceName: kafka
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: confluentinc/cp-kafka:7.5.2
          ports:
            - containerPort: 9092
          env:
            # Zookeeper
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "zookeeper-service.lastmile.svc.cluster.local:2181"

            # Broker ID must match statefulset ordinal
            - name: KAFKA_BROKER_ID
              value: "0"

            # INTERNAL + EXTERNAL listeners
            - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
              value: "true"

            - name: KAFKA_LISTENERS
              value: PLAINTEXT://0.0.0.0:9092

            - name: KAFKA_ADVERTISED_LISTENERS
              value: PLAINTEXT://kafka-service.lastmile.svc.cluster.local:9092

            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: PLAINTEXT:PLAINTEXT

            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: PLAINTEXT

            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"

            - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
              value: "1"

            - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
              value: "1"
#            - name: KAFKA_JMX_PORT
#              value: 9101
#            - name: KAFKA_JMX_HOSTNAME
#              value: localhost
#            - name: KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS
#              value: "0"
#            - name: KAFKA_LOG_RETENTION_HOURS
#              value: "168"
#
#            - name: KAFKA_LOG_SEGMENT_BYTES
#              value: "1073741824"

          volumeMounts:
            - name: data
              mountPath: /var/lib/kafka/data

  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi